language: java
dist: trusty
addons:
    sonarcloud:
        organization: steinarb-github
        token: $SONAR_TOKEN
script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
    - mvn cobertura:cobertura coveralls:report
